config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :products
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :returen
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clean
      post :checkout
    end
  end

  resources :cart_items
  resources :orders do
    member do
      post :pay_with_alipay
      post :pay_with_wechat
      post :apply_to_cancel
    end
  end

  namespace :account do
    resources :orders
  end

  root 'products#index'
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin"
  before_action :authenticate_user!
  

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, :image)
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
     if !current_cart.products.include? (@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "成功加入购物车"
    else
      flash[:warning] = "购物车内已有此商品"
    end
    redirect_to :back
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<h1>Edit Product </h1>
<%= simple_form_for [:admin, @product] do |f| %>

<div class="group">
  <%= f.input :title %>
</div>

<div class="group">
  <%= f.input :description %>
</div>

<div class="group">
  <%= f.input :quantity %>
</div>

<div class="group">
  <%= f.input :price %>
</div>

<% if @product.image.present? %>
  <span>目前商品图</span> <br>
  <%= image_tag(@product.image.thumb.url) %>
<% end %>

<div class="group">
  <%= f.input :image, as: :file %>
</div>

<%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/index.html.erb
<h2> Products list </h2>
<div class="pull-right" style="padding-bottom: 20px;">
  <%= link_to("新增产品", new_admin_product_path, class: "btn btn-primary btn-sm") %>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>#</th>
      <th width= "220">Product Pic </th>
      <th>Name </th>
      <th>Price </th>
      <th width= "100"> Options </th>
    </tr>
  </thead>
  <tbody>
   <% @products.each do |product| %>
   <tr>
     <td>
       <%= product.id %>
     </td>
     <td>
       <%= link_to product_path(product) do %>
        <% if product.image.present? %>
         <%= image_tag(product.image.thumb.url, class: "thumbnail") %>
        <% else %>
         <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail") %>
        <% end %>
      <% end %>
    </td>
    <td>
      <%= product.title %>
    </td>
    <td>
      <%= product.price %>
    </td>
    <td>
      <%= link_to("Edit", edit_admin_product_path(product)) %>
    </td>
   </tr>
   <% end %>
  </tbody>
</table>

app/views/admin/products/new.html.erb
<h1>New Product </h1>
<%= simple_form_for [:admin, @product] do |f| %>

<div class="group">
  <%= f.input :title %>
</div>

<div class="group">
  <%= f.input :description %>
</div>

<div class="group">
  <%= f.input :quantity %>
</div>

<div class="group">
  <%= f.input :price %>
</div>

<div class="group">
  <%= f.input :image, as: :file %>
</div>

<%= f.submit "Submit", data: { disable_with: "Submitting..." } %>

<% end %>

app/views/admin/products/show.html.erb
<div class="row">
  <div class="col-md-6">
    <% if @product.image.present? %>
     <%= image_tag(@product.image.medium.url, class: "thumbnail") %>
    <% else %>
     <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
    <% end %>
  </div>

  <div class="col-md-6">
    <h2> <%= @product.title %> </h2>
    <div style="height: 100px">
      <p> <%= @product.description %> </p>
    </div>
    <div> 数量：<%= @product.quantity %> </div>
    <div class="product-price"> ￥ <%= @product.price %> </div>
    <div class="pull-right">
      <%= link_to("加入购物车", add_to_cart_product_path(@product), :method => :post, :class => "btn btn-danger btn-lg") %>
    </div>
  </div>
</div>